### ISSUE TITLE
no such file config .json

### ISSUE THREAD

**Issue by thaynos** [KorigamiK/kickassanime-downloader#2]
![image](https://user-images.githubusercontent.com/83282129/119464871-39d38c80-bd54-11eb-9983-dd738ffcf5c2.png)

**Comment by KorigamiK** [comment]
You need to change the names of file in the `Config` folder. Rename them by removing `.eg` from their names. Adjust their contents according to you first before moving on. 

Right not I haven't documented the steps in the Readme so I would
advice you to fist check you [This issue](https://github.com/KorigamiK/kickassanime-downloader/issues/1) where I explain most of the installation steps.

**Comment by KorigamiK** [comment]
Also you should first run 
```
pip install -r requirements.txt
```
Inside the downloaded folder.

**Comment by thaynos** [comment]
i did whatever u told
but im getting this issue now 
![image](https://user-images.githubusercontent.com/83282129/119516686-03b00000-bd88-11eb-9169-e89721071b27.png)

**Comment by thaynos** [comment]
i dint understand the kaa thign yet but ik it ahs something to do with path variable
im using a guest pc so i cant use path variable
will it effect much?

**Comment by KorigamiK** [comment]
Hey, thanks for the bug report. It seems like they have one of their domains taken down. I have updated the program to force it to use the correct one. You will need to download the program again and repeat the steps.

I suggest you to not search the anime name directly, try to search the series name first like `nanatsu` and then select the anime number from the table.

You should also check out `aiodownloader` by changing the downloader in your `.\Connfig\config.json` to `aiodownloader`
Tell me if it works.

**Comment by KorigamiK** [comment]
Also you can run 
```
python cli.py nanatsu --opt -1 --ep 1 --custom_server 2
```
just to stream the anime you want.
For this you need vlc or mpv in your path (you can search google for steps).

Change your `./Config/watch_config.json`.
For `VLC` you need:
```
{
...
"system": "nt",
...
}
```
For `MPV` you need:
```
{
...
"system": "MPV",
...
}
```
Run `python cli.py --help` to understand the commands

**Comment by thaynos** [comment]
> Hey, thanks for the bug report. It seems like they have one of their domains taken down. I have updated the program to force it to use the correct one. You will need to download the program again and repeat the steps.
> 
> I suggest you to not search the anime name directly, try to search the series name first like `nanatsu` and then select the anime number from the table.
> 
> You should also check out `aiodownloader` by changing the downloader in your `.\Connfig\config.json` to `aiodownloader`
> Tell me if it works.

![image](https://user-images.githubusercontent.com/83282129/119533535-fe0de680-bd96-11eb-957f-da5182528ba9.png)
this issue came now
also why did u add the .eg to the json files?

**Comment by thaynos** [comment]
![image](https://user-images.githubusercontent.com/83282129/119534534-16cacc00-bd98-11eb-99ed-d5a4e0264e66.png)
this issues comes up now
i dont want to stream only download
i did whatever u told me to do

**Comment by KorigamiK** [comment]
Ah, I see you've messed up the config file. You're missing a semicolon or comma somewhwere.
The reason so that you can run `git pull` without modifying your config files.
Copy and paste this to your `config.json`
```
{
    "WEBSITE_DOMAIN": ".rs",
    "priority": {
        "KICKASSANIMEV2": -3,
        "KICKASSANIMEX": -3,
        "MAGENTA02": -1,
        "MAGENTA13":-2,
        "BETA-SERVER": -1,
        "MOBILE-V2": -1,
        "HTML5": -1,
        "A-KICKASSANIME": -1,
        "KICKASSANIME1": -1,
        "BETASERVER3": 2
    },
    "max_subprocesses": 5,
    "not used downloader": "subprocess",
    "downloader": "aiodownloader",
    "not_used_servers":{
        "DR.HOFFMANN": -1,
        "THETA-ORIGINAL-V4": 0,
        "ORIGINAL-QUALITY-V2":0,
        "THETA-ORIGINAL": -1
    },
    "debug": true
}

```

**Comment by thaynos** [comment]
> Ah, I see you've messed up the config file. You're missing a semicolon or comma somewhwere.
> The reason so that you can run `git pull` without modifying your config files.
> Copy and paste this to your `config.json`
> 
> ```
> {
>     "WEBSITE_DOMAIN": ".rs",
>     "priority": {
>         "KICKASSANIMEV2": -3,
>         "KICKASSANIMEX": -3,
>         "MAGENTA02": -1,
>         "MAGENTA13":-2,
>         "BETA-SERVER": -1,
>         "MOBILE-V2": -1,
>         "HTML5": -1,
>         "A-KICKASSANIME": -1,
>         "KICKASSANIME1": -1,
>         "BETASERVER3": 2
>     },
>     "max_subprocesses": 5,
>     "not used downloader": "subprocess",
>     "downloader": "aiodownloader",
>     "not_used_servers":{
>         "DR.HOFFMANN": -1,
>         "THETA-ORIGINAL-V4": 0,
>         "ORIGINAL-QUALITY-V2":0,
>         "THETA-ORIGINAL": -1
>     },
>     "debug": true
> }
> ```

this is the default settings right?

**Comment by thaynos** [comment]
> The reason so that you can run `git pull` without modifying your config files.

i dint understand what this means can you explain?

**Comment by KorigamiK** [comment]
I got it, I'll fix this later but in the meantime you can just leave the episode starting and ending blank (just press `enter` key when asked) and everything should work.
You were missing a comma earlier

**Comment by thaynos** [comment]
oh ok lmao funny how a missing comma can make the script obsolete
btw great job on this sorry i cant get anything right

**Comment by KorigamiK** [comment]
> i dint understand what this means can you explain?

You are downloading the files manually for now right? 
If you were to get the repo using git
```
git clone https://github.com/KorigamiK/kickassanime-downloader
```
You can run `git pull` to fetch the latest changes automatically without needing to update the files manually.

> oh ok lmao funny how a missing comma can make the script obsolete

Thats just the nature of `json` files.

Also I should mention that this is how the quality index works in `config.json`
![photo_2021-05-25_22-16-59](https://user-images.githubusercontent.com/72932688/119536658-f1918a00-bda6-11eb-9599-89b2973c1803.jpg)
Adjust the numbers according to what quality you want.
Although I now realize writing this in the `readme` would be better but, oh well.

**Comment by thaynos** [comment]
i have to do git pull in the directory?
also where is that picture from?
is it the gui?
how do i get it?
i want to install as 720p or 480p how do i do that?

**Comment by thaynos** [comment]
its stuck on this for the past 15 mins??
![image](https://user-images.githubusercontent.com/83282129/119538847-92c71300-bd9c-11eb-95cb-91cdbd5f7bdc.png)
edit- still shwing the same thing 30 mins later

**Comment by thaynos** [comment]
2 hours later......

**Comment by KorigamiK** [comment]
you should get 480p for now. You should check what location you have set in `to_update.json` for how much you have already downloaded. Don't tell me you didn't add your own location.


> also where is that picture from?

It's from the original website.
If the downloads are getting stuck, you should probably get back to setting your downloader to `subprocess` in `config.json`

**Comment by thaynos** [comment]
> you should get 480p for now. You should check what location you have set in `to_update.json` for how much you have already downloaded. Don't tell me you didn't add your own location.

bruhhhh i dont know shit about javascript i dint change anything lmfao. also doesnt 720p work?

> It's from the original website.

which website?

> If the downloads are getting stuck, you should probably get back to setting your downloader to `subprocess` in `config.json`

**Comment by KorigamiK** [comment]
Then please change the 
```
download_location 
```
In `to_update.json` where you want it. You would also need to escape the backlash like ```C:\\Downloads ``` you need to put the backslash twice.

**Comment by KorigamiK** [comment]
Changing kickassanimex to 1 in config.json should give you 720p

**Comment by thaynos** [comment]
> Then please change the
> 
> ```
> download_location 
> ```
> 
> In `to_update.json` where you want it. You would also need to escape the backlash like `C:\\Downloads ` you need to put the backslash twice.

i cant find the download location text?
```
{
    "WEBSITE_DOMAIN": ".rs",
    "priority": {
        "KICKASSANIMEV2": -3,
        "KICKASSANIMEX": 1,
        "MAGENTA02": -1,
        "MAGENTA13":-2,
        "BETA-SERVER": -1,
        "MOBILE-V2": -1,
        "HTML5": -1,
        "A-KICKASSANIME": -1,
        "KICKASSANIME1": -1,
        "BETASERVER3": 2
    },
    "max_subprocesses": 5,
    "not used downloader": "subprocess",
    "downloader": "aiodownloader",
    "not_used_servers":{
        "DR.HOFFMANN": -1,
        "THETA-ORIGINAL-V4": 0,
        "ORIGINAL-QUALITY-V2":0,
        "THETA-ORIGINAL": -1
    },
    "debug": true
}
```

**Comment by KorigamiK** [comment]
I SAID `to_update.json`  Please read carefully.

**Comment by thaynos** [comment]
damnit sorry i dint read properly
forgive me for stupidding
where did i miss the comma :(
![image](https://user-images.githubusercontent.com/83282129/119648896-0a478180-be33-11eb-9c4f-aeecec521017.png)

```
{
    "WEBSITE_DOMAIN": ".rs",
    "priority": {
        "KICKASSANIMEV2": -3,
        "KICKASSANIMEX": 1,
        "MAGENTA02": -1,
        "MAGENTA13":-2,
        "BETA-SERVER": -1,
        "MOBILE-V2": -1,
        "HTML5": -1,
        "A-KICKASSANIME": -1,
        "KICKASSANIME1": -1,
        "BETASERVER3": 2
    },
    "max_subprocesses": 5,
    "not used downloader": "aiodownloader",
    "downloader": "subprocess",
    "not_used_servers":{
        "DR.HOFFMANN": -1,
        "THETA-ORIGINAL-V4": 0,
        "ORIGINAL-QUALITY-V2":0,
        "THETA-ORIGINAL": -1
    },
    "debug": true
}
```

```
{
    "anime": {
        "https://www2.kickassanime.rs/anime/the-promised-neverland-season-2-251047": 6,
        "https://www2.kickassanime.rs/anime/sorcery-fight-723619": 18,
        "https://www2.kickassanime.rs/anime/dr-stone-stone-wars-802545/episode-01-852057": 5,
        "https://www2.kickassanime.rs/anime/horimiya-405153": 6,
        "https://www2.kickassanime.rs/anime/mushoku-tensei-jobless-reincarnation-280419": 6,
        "https://www2.kickassanime.rs/anime/rezero-kara-hajimeru-isekai-seikatsu-2nd-season-part-2-613847": 6,
        "https://www2.kickassanime.rs/anime/the-low-tier-character-tomozaki-kun-382592": 6,
        "https://www2.kickassanime.rs/anime/wonder-egg-priority-545544": 5
    },
    "download_location": "C:\\Users\GUEST123\Downloads\misc\downlaoders\kickassanime-downloader-master\kickassanime-downloader-master\downloaded",
    "pause_on_complete": true
}
```

**Comment by KorigamiK** [comment]
No, it should be
```

"download_location": "C:\\Users\\GUEST123\\Downloads\\misc\\downlaoders\\kickassanime-downloader-master\\kickassanime-downloader-master\\downloaded",

```

**Comment by thaynos** [comment]
thx for ur help
i think its working
altho some episodes arent working
![image](https://user-images.githubusercontent.com/83282129/119668580-5b15a500-be48-11eb-8c76-c1565ddb856d.png)

**Comment by thaynos** [comment]
this is exactly what i want actually
![image](https://user-images.githubusercontent.com/83282129/119671840-25be8680-be4b-11eb-9c06-c923868664ea.png)
only problem is that all episodes dint get downloaded :(
if it was only for that this script would perfect for my needs

**Comment by thaynos** [comment]
never mind actually the quality is really bad even if its 720p
its really blurry and barely watcheable
guess ill stick with 1080p

**Comment by thaynos** [comment]
how to switch back to 1080p?
sry for the trouble

**Comment by thaynos** [comment]
im pretty sure its the websites fault but theres a clear quality dif between animepahe and kickassanime
![image](https://user-images.githubusercontent.com/83282129/119673056-20ae0700-be4c-11eb-9ffd-3c87e6c5ab41.png)
![image](https://user-images.githubusercontent.com/83282129/119673067-2277ca80-be4c-11eb-98b4-9d5548605c47.png)
theres also a audio quality difference

**Comment by KorigamiK** [comment]
> Also I should mention that this is how the quality index works in `config.json`
> ![photo_2021-05-25_22-16-59](https://user-images.githubusercontent.com/72932688/119536658-f1918a00-bda6-11eb-9599-89b2973c1803.jpg)

Changing the value of `kickassanimex` to `0` or `1` in `config.json` will give you `1080p` or `720p` respectively. 
Right now you are downloading all the episodes in `480p` (I think) since that's the default. If you still believe that the quality is still not good enough you can try out other servers from the website and then add them above `kickassanimex`.

> only problem is that all episodes dint get downloaded :(

I can't do anything about that, if the download links are not available on the website then you can only stream them (you can use the `--encode` flag to download them and encode them yourself). Although I am thinking of adding a feature that also downloads them.

**Comment by KorigamiK** [comment]
Also, try to run the script again. I was able to download all the episodes no problem.

**Comment by thaynos** [comment]
> > Also I should mention that this is how the quality index works in `config.json`
> > ![photo_2021-05-25_22-16-59](https://user-images.githubusercontent.com/72932688/119536658-f1918a00-bda6-11eb-9599-89b2973c1803.jpg)

ohhh thats what the -1 and -3s mean
i understand now thx for this

> Changing the value of `kickassanimex` to `0` or `1` in `config.json` will give you `1080p` or `720p` respectively.

understood thx

> Right now you are downloading all the episodes in `480p` (I think) since that's the default. If you still believe that the quality is still not good enough you can try out other servers from the website and then add them above `kickassanimex`.

it is 720p only i checked in vlc video info. maybe maybe its 480p but made to fit in a 720p canvas? that still doesnt explain the audio quality dif. ofc its the sites issue with encoding maybe(?)
wdym different servers? which website? which domain kickassanime is used? im rather scared of changing the config files cuz i might mess up something minute like a comma 💀 

> > only problem is that all episodes dint get downloaded :(
> 
> I can't do anything about that, if the download links are not available on the website then you can only stream them (you can use the `--encode` flag to download them and encode them yourself). Although I am thinking of adding a feature that also downloads them.

ah ok thats sad :(


> > also where is that picture from?
> 
> It's from the original website.

which website?

**Comment by thaynos** [comment]
also isnt there a way to change the quality and other settings using the script itself instead of changing the json file again and again?

**Comment by KorigamiK** [comment]
its kickassanime.ru you should have figured that out by now

**Comment by KorigamiK** [comment]
> 
> 
> also isnt there a way to change the quality and other settings using the script itself instead of changing the json file again and again?

not right now

**Comment by thaynos** [comment]
alr i downloaded all episodes in 1080p and its significantly better quality now. much more watcheable. although its still kinda bad but thats cuz the animation trash this season.
thx for ur help :D

**Comment by KorigamiK** [comment]
Glad to be of your help.
