### ISSUE TITLE
Issue with downloading an anime

### ISSUE THREAD

**Issue by mglaserg** [KorigamiK/kickassanime-downloader#4]
Hi me again! I was trying to download pretty boy detective club from episode 8 until 12. It just said:

> Getting episode 12
> Getting episode 11
> Getting episode 10
> Getting episode 09
> Getting episode 08

and then it just quit. So I thought what if I tried one episode like episode 8 and so it gave me a link and quit because the quality I provided was out of range. I clicked through the link and it took me to a blank page. 

Here is the full output from the program

> Enter choice number: 1

> Search And Download
> Enter anime name: pretty boy
> 0 Pretty Boy Detective Club
> Enter anime number: 0
> Pretty Boy Detective Club
> Skip episode numbers to default to first or latest episode
> Enter Episode to start from: 8
> Enter Episode to end from: 8
> pretty boy detective club
> Getting episode 08
> Starting episode 08
> KICKASSANIMEX
> https://kaa-play.me/KickAssAnimeX/d.php?link=lMPAFDFNWf9W25yVn@LhO7oeF@wBSox4WqtPzgBIVgE8yAbIltGw1UFPCtgItlg=
> Enter quality number: 0
> Traceback (most recent call last):
>   File ".\cli.py", line 88, in <module>
>     asyncio.get_event_loop().run_until_complete(choices[result]())
>   File "C:\Users\mglas\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 587, in run_until_complete
>     return future.result()
>     download_location=download_location,
>   File "C:\Users\mglas\Documents\GitHub\kickassanime-downloader\kickassanime_scraper.py", line 466, in automate_scraping
>     links_and_names_and_headers = await asyncio.gather(*download_tasks)
>   File "C:\Users\mglas\Documents\GitHub\kickassanime-downloader\kickassanime_scraper.py", line 225, in get_download
>     await a.get_final_links(final[1])
>   File "C:\Users\mglas\Documents\GitHub\kickassanime-downloader\utilities\pace_scraper.py", line 246, in get_final_links
>     await scraper._magenta(self, link)
>   File "C:\Users\mglas\Documents\GitHub\kickassanime-downloader\utilities\pace_scraper.py", line 225, in _magenta
>     self.final_dow_urls += [link_and_quality[self.quality][0]]
> IndexError: list index out of range

I wanted to let you know about this. Also if this looks weird I'm sorry

**Comment by KorigamiK** [comment]
I sorry that you had to see this error. Unfortunately this is not the fault of the program. As you can check for yourself by clicking the link of the server yourself, there are no download links present.

Anyway I have fixed the crash now and you see an error whenever this happens again. You can pull the latest changes from the repository now.

To combat this you can see the available servers yourself and then move `KICKASSANIMEX` to the bottom of the priority list in `config.json`. for example; if it is above some of the available servers right now like this:
```
{
    ...
    "priority": {
        "KICKASSANIMEV2": -3,
        "KICKASSANIMEX": -3,
        "MAGENTA02": -1,
        "MAGENTA13":-2,
        "BETA-SERVER": -1,
        "MOBILE-V2": -1,
        "HTML5": -1,
        "A-KICKASSANIME": -1,
        "KICKASSANIME1": -1,
        "BETASERVER3": 2
    },
    ...
}
```

You can move it down like this:
```
{
    ...
    "priority": {
        "KICKASSANIMEV2": -3,
        "MAGENTA02": -1,
        "MAGENTA13":-2,
        "BETA-SERVER": -1,
        "MOBILE-V2": -1,
        "HTML5": -1,
        "A-KICKASSANIME": -1,
        "KICKASSANIME1": -1,
        "BETASERVER3": 2,
        "KICKASSANIMEX": -3,
    },
    ...
}
```
Hope you are able to understand

**Comment by KorigamiK** [comment]
By the way, you can now run `kaa download` and `kaa update` or `python cli.py download` and `python cli.py update` to directly perform the respective actions without going through the menu! Cheers

**Comment by mglaserg** [comment]
Oh yeah I figured that it wasn't the fault of the program. I will retry with the KICKASSANIMEX having a lower server priority. And awesome! Thank you for doing all of this
