### ISSUE TITLE
It does not follow known pattern, please make an issue on github.

### ISSUE THREAD

**Issue by BackThrowTheBaguetteBrawler** [KorigamiK/kickassanime-downloader#5]
Though the playing feature works fine, the downloading feature gives me this error.

~/c/kickassanime-downloader (master)> python3 cli.py

Selectmenu not installed, using basic menu layout.
What would you like?
0 Play Episode
1 Search And Download
2 Autoupdate Library
3 Fetch Latest
4 Check For Updates
5 See Config

Enter choice number: 1
Search And Download
Enter anime name: jojo  
0 JoJo no Kimyou na Bouken: Diamond wa Kudakenai
1 JoJo no Kimyou na Bouken: Stardust Crusaders
2 JoJo no Kimyou na Bouken: Stardust Crusaders 2nd Season
3 JoJo no Kimyou na Bouken (TV)
4 JoJo's Bizarre Adventure (2000) (Dub)
5 JoJo's Bizarre Adventure (2012) (Dub)
6 JoJo's Bizarre Adventure (Dub)
7 JoJo no Kimyou na Bouken: Ougon no Kaze
8 JoJo no Kimyou na Bouken: Diamond wa Kudakenai (Dub)
9 JoJo no Kimyou na Bouken: Ougon no Kaze (Dub)
Enter anime number: 9
JoJo no Kimyou na Bouken: Ougon no Kaze (Dub)
Skip episode numbers to default to first or latest episode
Enter Episode to start from: 1
Enter Episode to end from: 1
jojo no kimyou na bouken ougon no kaze dub
BETA-SERVER
https://beststremo.xyz/Beta-Server/d.php?link=lMPAFDFNWf9Y34GaiuH5eacCW@ERWpwwGrhbm10ACUF9yAfGi9C11xUBUZZb4kwUxhTKBJsFGb7kuY4N9bjBiR2kFECNjJ@9U6sDYdfWxJsP
Bad serverlink https://beststremo.xyz/Beta-Server/d.php?link=lMPAFDFNWf9Y34GaiuH5eacCW@ERWpwwGrhbm10ACUF9yAfGi9C11xUBUZZb4kwUxhTKBJsFGb7kuY4N9bjBiR2kFECNjJ@9U6sDYdfWxJsP. It does not follow known pattern, please make an issue on github.
Cannot download jojo no kimyou na bouken ougon no kaze dub episode 01

download now y/n?: y
No downloads found

**Comment by KorigamiK** [comment]
Thank you for making the issue. I'll try to fix it as soon as I can. In the meantime you could try decrease the priority of beta-server on your config file.

**Comment by KorigamiK** [comment]
The error has been fixed. Please pull the latest changes from the repository either from the cli menu or by manually downloading the new files.

The update also includes a new commands section to the help section so you can also try to run `python3 cli.py -h`

Let me know if everything works fine.

**Comment by BackThrowTheBaguetteBrawler** [comment]
Thank you for fixing the initial problem. i'm getting a different problem now when trying to use the program.
~/c/kickassanime-downloader (master)> python3 cli.py

Selectmenu not installed, using basic menu layout.
What would you like?
0 Play Episode
1 Search And Download
2 Autoupdate Library
3 Fetch Latest
4 Check For Updates
5 See Config

Enter choice number: 1
Search And Download
Enter anime name: jojo
0 JoJo no Kimyou na Bouken: Diamond wa Kudakenai
1 JoJo no Kimyou na Bouken: Stardust Crusaders
2 JoJo no Kimyou na Bouken: Stardust Crusaders 2nd Season
3 JoJo no Kimyou na Bouken (TV)
4 JoJo's Bizarre Adventure (2000) (Dub)
5 JoJo's Bizarre Adventure (2012) (Dub)
6 JoJo's Bizarre Adventure (Dub)
7 JoJo no Kimyou na Bouken: Ougon no Kaze
8 JoJo no Kimyou na Bouken: Diamond wa Kudakenai (Dub)
9 JoJo no Kimyou na Bouken: Ougon no Kaze (Dub)
Enter anime number: 9
JoJo no Kimyou na Bouken: Ougon no Kaze (Dub)
Skip episode numbers to default to first or latest episode
Enter Episode to start from: 1
Enter Episode to end from: 2
jojo no kimyou na bouken ougon no kaze dub
BETA-SERVER
https://beststremo.xyz/Beta-Server/d.php?link=lMPAFDFNWf9Y34GaiuH5eacCW@ERWpwwGrhbm10ACUF9yAfGi9C11xUBUZZb4kwUxhTKBJsFGb7kuY4N9bjBiR2kFECNjJ@9U6sDYaaRms8Di6qH
BETA-SERVER
https://beststremo.xyz/Beta-Server/d.php?link=lMPAFDFNWf9Y34GaiuH5eacCW@ERWpwwGrhbm10ACUF9yAfGi9C11xUBUZZb4kwUxhTKBJsFGb7kuY4N9bjBiR2kFECNjJ@9U6sDYdfWxJsP

download now y/n?: y
Starting all downloads for jojo no kimyou na bouken ougon no kaze dub
Please Wait...
FileNotFoundError(2, 'No such file or directory')
FileNotFoundError(2, 'No such file or directory')

**Comment by KorigamiK** [comment]
Ok, I would like you to go to your config.json and the debug option to true and then paste the output here again. That would make it easier for me to discuss the problem.

**Comment by BackThrowTheBaguetteBrawler** [comment]
alright, here is the new output
python3 cli.py

Selectmenu not installed, using basic menu layout.
What would you like?
0 Play Episode
1 Search And Download
2 Autoupdate Library
3 Fetch Latest
4 Check For Updates
5 See Config

Enter choice number: 1
Search And Download
Enter anime name: jojo
0 JoJo no Kimyou na Bouken: Diamond wa Kudakenai
1 JoJo no Kimyou na Bouken: Stardust Crusaders
2 JoJo no Kimyou na Bouken: Stardust Crusaders 2nd Season
3 JoJo no Kimyou na Bouken (TV)
4 JoJo's Bizarre Adventure (2000) (Dub)
5 JoJo's Bizarre Adventure (2012) (Dub)
6 JoJo's Bizarre Adventure (Dub)
7 JoJo no Kimyou na Bouken: Ougon no Kaze
8 JoJo no Kimyou na Bouken: Diamond wa Kudakenai (Dub)
9 JoJo no Kimyou na Bouken: Ougon no Kaze (Dub)
Enter anime number: 9
JoJo no Kimyou na Bouken: Ougon no Kaze (Dub)
Skip episode numbers to default to first or latest episode
Enter Episode to start from: 1
Enter Episode to end from: 1
jojo no kimyou na bouken ougon no kaze dub
Getting episode 01
Starting episode 01
BETA-SERVER
https://beststremo.xyz/Beta-Server/d.php?link=lMPAFDFNWf9Y34GaiuH5eacCW@ERWpwwGrhbm10ACUF9yAfGi9C11xUBUZZb4kwUxhTKBJsFGb7kuY4N9bjBiR2kFECNjJ@9U6sDYdfWxJsP

download now y/n?: y
Starting all downloads for jojo no kimyou na bouken ougon no kaze dub
Please Wait...
FileNotFoundError(2, 'No such file or directory')
[('https://beststremo.xyz/redirector.php?link=aHR0cHM6Ly9yZWRpcmVjdG9yLmdvb2dsZXZpZGVvLmNvbS92aWRlb3BsYXliYWNrP2V4cGlyZT0xNjMzNTUwMzc1JmVpPXA0OWRZYWlOT3RXRV85RVB1TWlSOEFFJmlwPTUxLjIxMC4xMDEuMCZpZD1iNjgxOGQ1MDI0MTFjYzY3Jml0YWc9MTgmc291cmNlPWJsb2dnZXImbWg9XzgmbW09MzEmbW49c24tMjVnbGVuN3kmbXM9YXUmbXY9dSZtdmk9NCZwbD0yNCZzdXNjPWJsJm1pbWU9dmlkZW8vbXA0JnZwcnY9MSZkdXI9MTQyNC4xOTUmbG10PTE1OTg3Mzg0MjI4MTM2NDQmbXQ9MTYzMzUyMTAzOSZ0eHA9MTMxMTIyNCZzcGFyYW1zPWV4cGlyZSxlaSxpcCxpZCxpdGFnLHNvdXJjZSxzdXNjLG1pbWUsdnBydixkdXIsbG10JnNpZz1BT3EwUUo4d1JRSWdmQWFxakpoVFNVZ05JVUNwc0ZFM19IZDZxYThVLUt2N3NUNkhRc01hU24wQ0lRRGFVS3d0SlgzeTF3Yy1UcFRTNzJpbmRIYkZ5NkZqODFvWFNWQnZMaEFBREElM0QlM0QmbHNwYXJhbXM9bWgsbW0sbW4sbXMsbXYsbXZpLHBsJmxzaWc9QUczQ194QXdSUUlnTGppeGQ2b1RUaUJac2ltaTRUYm44dGg3QmFoMnpCUV9QUUhYaTRyRlBZMENJUUNFLXprMHVDVElGa1l2RndKMzhQczFoSjJ0NkxBRmxmQkhKQ0ZyUDZSRi1BJTNEJTNE', 'jojo no kimyou na bouken ougon no kaze dub ep_01.mp4', None)]

**Comment by KorigamiK** [comment]
Okay, can I see your to_update.json file in the config/ folder

**Comment by KorigamiK** [comment]
I think you have not correctly looked at the config files. Please open each one of them and modify them accordingly. If you are not sure what an option does then you can ask or just use the default value. 

I suspect you have not modified the download_directory in your to update.json

**Comment by KorigamiK** [comment]
Sorry. Yes I believe there was also an error that the downloads didn't start using aiodownloader. It should be fixed now. I suggest that you update to the latest version.

**Comment by BackThrowTheBaguetteBrawler** [comment]
thank you so much for everything
it works now
i looked at the config file and concluded that i am an idiot. the download directory was not changed.
