### ISSUE TITLE
can't download

### ISSUE THREAD

**Issue by Fr4nzJ** [KorigamiK/kickassanime-downloader#7]
Hi, I've been having trouble in downloading an anime because whenever I pick one and start downloading it gets an error. Its like this:

Selectmenu not installed, using basic menu layout.
What would you like?
0 Play Episode
1 Search And Download
2 Autoupdate Library
3 Fetch Latest
4 Check For Updates
5 See Config

Enter choice number: 1
Search And Download
Enter anime name: yuragi
0 Yuragi-sou no Yuuna-san
1 Yuragi-sou no Yuuna-san OVA (Uncensored)
2 Yuragi-sou no Yuuna-san (Uncensored)
Enter anime number: 1
Yuragi-sou no Yuuna-san OVA (Uncensored)
Skip episode numbers to default to first or latest episode
Enter Episode to start from: 1
Enter Episode to end from: 4
yuragi sou no yuuna san ova

download now y/n?: y
No downloads found
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001C616A2C310>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001C616A2C310>
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by KorigamiK** [comment]
Thank you for bringing this crash to my attention. The error has been resolved in the latest update and should work without crashes. Please try to check for updates from the cli itself (or manually).
If you feel like the error has been resolved feel free to close this issue, else give me an update on the new errors.

Regards.

**Comment by Fr4nzJ** [comment]
Hi again, after I updated, it can finally find the episodes but there some of is still cannot. Anyways, thanks for the help and here is the result on the fix:

Selectmenu not installed, using basic menu layout.
What would you like?
0 Play Episode
1 Search And Download
2 Autoupdate Library
3 Fetch Latest
4 Check For Updates
5 See Config

Enter choice number: 1
Search And Download
Enter anime name: uragi
0 Yuragi-sou no Yuuna-san
1 Yuragi-sou no Yuuna-san OVA (Uncensored)
2 Yuragi-sou no Yuuna-san (Uncensored)
Enter anime number: 1
Yuragi-sou no Yuuna-san OVA (Uncensored)
Skip episode numbers to default to first or latest episode
Enter Episode to start from: 1
Enter Episode to end from: 4
yuragi sou no yuuna san ova
KICKASSANIMEX
https://beststremo.com/KickAssAnimeX/d.php?link=lMPAFDFNWf9W25yVn@LhO7oeF@wBSox4WqtPzgBIVgE8yAbIlNq21k9CB9MNtFA=
KICKASSANIMEV2
https://beststremo.com/Kickassanimev2/dl.php?id=Nnh2WFNtS2ZPQTh2V1lBS2pLWUx5VXljMkVjL1cvSDdzOGZVSUhvdzdFZVQrL040ZjhnZHUya1hjUU5sek9JUA&sig=79D324362324264EF62CC3340BCEEBCE345C6C19
KICKASSANIMEV2
https://beststremo.com/Kickassanimev2/dl.php?id=ejFRS2JsRm5wY0tpZ2R2NndCRndkK1VkdWpJdmZqVlp0eVJCN2ZtT1IwUnE1Wk1wOXRadlRNUUlDNFY4NVl3Wg&sig=B06A5422528523F186AFEDA74E2ADDDC4DAC68C5
Index 2 not found in 360p [Mp4], 720p [Mp4]
Defaulting to 720p [Mp4]
MOBILE-V2
https://beststremo.com/mobile-v2/devplayer.php?link=lMPAFDFNWf9IzI2SjrX7NaoPQOdZSZwtG7tPmAAdSFx8rHS595nCohszR4Zjtist9FTQK5kAR@DTn85Y25yWnkb/H0@OlMH4X75fdozNxpcXmA==&sub=
Cannot download yuragi sou no yuuna san ova episode 01

**Comment by KorigamiK** [comment]
Hello, this error seems to be a result of a server error, I am not able to fix this. However whenever you find such problems in downloading you can change the priority of the server to be lower in the config file. For example, in this case since you are facing problems with `Mobile-v2` you can put it below `html5` server. so the `config.json`

```json
{
    "WEBSITE_DOMAIN": ".ro",
    "check_updates": false,
    "priority": {
        "KICKASSANIMEV2": 2,
        "KICKASSANIMEX": 2,
        "MAGENTA02": -1,
        "MAGENTA13":-2,
        "BETA-SERVER": -1,
        "HTML5": -1,
        "MOBILE-V2": -1,
        "A-KICKASSANIME": -1,
        "KICKASSANIME1": -1,
        "BETASERVER3": 2
    },
    "max_subprocesses": 5,
    "downloader": "aiodownloader",
    "not used downloader": "subprocess",
    "not_used_servers":{
        "DR.HOFFMANN": -1,
        "THETA-ORIGINAL-V4": 0,
        "ORIGINAL-QUALITY-V2":0,
        "THETA-ORIGINAL": -1
    },
    "debug": true
}
```
This should mitigate the current problem. Note that when sending error messages, you should always set the `debug` property in `config.json` to be true to give more insight into the error.
